context:
  name: verspec
  version: 0.1.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.io/packages/source/${{ name[0] }}/${{ name }}/verspec-${{ version }}.tar.gz
  sha256: c4504ca697b2056cdb4bfa7121461f5a0e81809255b41c03dda4ba823637c01e

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

tests:
  - python:
      imports:
        - verspec
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
    script:
      - pip check

about:
  summary: Flexible version handling
  license: BSD-2-Clause
  license_file: LICENSE
  homepage: https://github.com/jimporter/verspec

extra:
  recipe-maintainers:
    - hadim
